### ISSUE TITLE
The app is not unixlike

### ISSUE THREAD

**Issue by PurHur** [peterwankman/fdd#1]
there is no computer readable output. YOU NEED TO FIX THIS **ASAP**

**Comment by PurHur** [comment]
pls respond ASAP
cant wait to use it in our productive enterprise environment

**Comment by peterwankman** [comment]
Giev patch or gtfo

**Comment by peterwankman** [comment]
Program issue fixed with commit e217501fcf8156270e0ef57905d838a0f2493cb4
PurHur's issues will never be fixed.
